replicaCount: 1
image:
  repository: ghcr.io/shareify-project/shareify-user-service
  pullPolicy: Always
  tag: "34af58f"
imagePullSecrets:
  - name: ghcr-secret
env:
  databasePath: "/app/data/user.db"
  jwtSecret: "change-me-secret-key"
service:
  type: ClusterIP
  port: 8000
persistence:
  enabled: true
  storageClass: "nfs-client"
  size: 1Gi
  mountPath: /app/data
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 16Mi

config: {}
secrets: {}


