apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
data:
  {{- if .Values.env }}
  DATABASE_URL: {{ .Values.env.databaseUrl | quote }}
  {{- end }}
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
