apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
data:
  # Only add DATABASE_PATH if the .Values.env object exists
  {{- if .Values.env }}
  DATABASE_PATH: {{ .Values.env.databasePath | default "/app/data/db.db" | quote }}
  {{- end }}
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
