name: User Service CI Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sast-scan:
    uses: Shareify-Project/shareify-workflows/.github/workflows/sast.yml@main
    secrets: inherit

  sca-scan:
    # needs: sast-scan
    uses: Shareify-Project/shareify-workflows/.github/workflows/sca.yml@main
    secrets: inherit

  build-and-push:
    # # needs: sca-scan
    permissions:
      contents: read
      packages: write
    uses: Shareify-Project/shareify-workflows/.github/workflows/build-and-push.yml@main
    with:
      image_name: shareify-user-service
    secrets: inherit


